version: '3'
services:
  mysql-server:
    image: mysql:latest
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
    - "3306:3306"
  front-end:
    image: gneiss-front:latest
    ports:
      - 3000:3000
  back-end:
    image: gneiss-back:latest
    ports:
      - 8080:8080
