version: '3'
volumes:
  output:
services:
  mysql-server:
    image: mysql:latest
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    ports:
      - ${MYSQL_PORT}:3306
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
  back-end:
    image: gneiss-back:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_HOST: mysql-server
      MYSQL_PORT: ${MYSQL_PORT}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - output:/output
    ports:
      - ${BACKEND_PORT}:8080
    links:
      - mysql-server 
      - redis