name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ ".github/**", "docs/**", "**/.gitignore", "build.sh", "clean.sh", "test.sh", "CONTRIBUTORS", "docker-compose.yaml", "LICENSE", "README.MD", "**/Dockerfile", "test" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ ".github/**", "docs/**", "**/.gitignore", "build.sh", "clean.sh", "test.sh", "CONTRIBUTORS", "docker-compose.yaml", "LICENSE", "README.MD", "**/Dockerfile" ]

jobs:
  build-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Setu up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - name: Build front-end && back-end
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Run test and linters
        run: |
          chmod +x test.sh
          ./test.sh
