name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  front-end-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm --prefix ./front-end install ./front-end
      - run: npm --prefix ./front-end run build ./front-end
  
  back-end-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn package -f back-end/pom.xml -DskipTests
      
  
  front-end-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm --prefix ./front-end install ./front-end
      - run: CI=true npm --prefix ./front-end test -- --coverage ./front-end
      - run: npx --prefix ./front-end prettier ./front-end/src

  back-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn test -f back-end/pom.xml
      - run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: run ktlint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true
  
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t back-end:latest -f back-end/Dockerfile .
      - run: docker build -t front-end:latest -f front-end/Dockerfile .
