name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm --prefix ./front-end install ./front-end
      - run: npm --prefix ./front-end run build ./front-end
      - run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: run ktlint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true
  
  test: 
    runs-on: ubuntu-latest
      
    strategy:
      matrix:
        node-version: [18.x]
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm --prefix ./front-end install ./front-end
      - run: CI=true npm --prefix ./front-end test -- --coverage ./front-end
      - run: npx --prefix ./front-end prettier ./front-end/src
